name: 'ApiGen Docs'
description: 'Simple Github Action Which Helps You To Generate PHP Code Documentation Website Using ApiGen'
author: 'varunsridharan'
branding:
  icon: 'hard-drive'
  color: 'green'
inputs:
  push_to_branch:
    description: 'Which Branch/Folder To Push'
    default: 'gh-pages'
  before_cmd:
    description: 'Command To Run Before ApiGen'
    default: ''
  after_cmd:
    description: 'Command To Run After ApiGen'
    default: ''
  auto_push:
    description: 'if set to yes then it auto pushes latest source to current repo with the push_to_branch'
    default: 'yes'
  output_folder:
    description: 'Custom output folder if auto_push is disabled'
    default: ''
  source_folder:
    description: 'Custom Source Folder if auto_push is disabled'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.push_to_branch }}
    - ${{ inputs.before_cmd }}
    - ${{ inputs.after_cmd }}
    - ${{ inputs.auto_push }}
    - ${{ inputs.output_folder }}
    - ${{ inputs.source_folder }}